name: Build sitemap.xml

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate sitemap.xml
        run: |
          BASE="https://${GITHUB_REPOSITORY_OWNER}.github.io/${GITHUB_REPOSITORY#*/}/"
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" > sitemap.xml
          echo "<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">" >> sitemap.xml
          for f in $(git ls-files '*.html'); do
            echo "<url><loc>${BASE}${f}</loc></url>" >> sitemap.xml
          done
          echo "</urlset>" >> sitemap.xml
      - name: Commit sitemap
        run: |
          git config user.name "DMS Automations"
          git config user.email "noreply@example.com"
          git add sitemap.xml
          git commit -m "build: update sitemap.xml" || echo "No changes"
          git push
